### ISSUE TITLE
peer-to-peer code reviews/day3

### ISSUE THREAD

**Issue by haftamudesta** [Feliverse/JavaScript-Capston-Project#26]
you did a great job in implementing the requirements of the project. 
to highlight some:
-no linter error 
-Professional README file 
-good use of git flow 

Required Changes 
when I click the comment button the popup window is not according to the wire frame. please update it according to the wireframe provided.
the close button is not clearly visible. kindly make it clear.
Optional suggestions
when I click all the links in your nav bar all are not working except the Home. kindly implement them.

**Comment by Feliverse** [comment]
Hi @haftamudesta , all required changed was dued
Thank you
